%Michael Craig
%January 19, 2015
%This script opens up spreadsheets that contain energy consumption and
%savings data per state generated by the EPA for the Clean Power Plan. This
%data is used to determine how demand should be changed in each state under
%that scenario. 

function [demandchangeproportions,demandbeforeee2013]=CalculateEESavingsFromIPMScenarios(demandscenarioforanalysis,...
    statesforanalysis,scaleenergyefficiencysavings, pc)
%INPUT: demandscenarioforanalysis is a number that represents annual EE
%incremental savings as %age. statesforanalysis is a cell array w/ the full
%name of states that are to be analyzed in each row, and each col has the 
%change in demand for a given scenario. scaleenergyefficiencysavings scales
%the cumulative % energy efficiency savings in 2030, in case I want to use,
%say, 0.5% per year EE as opposed to the roughly 1% per year EE 
%OUTPUT: demandchangeproportions: a cell array that contains the proportional change in BAU 2012
%sales to post-EE 2030 sales as a share of BAU 2012 sales. This data can be
%directly applied to 2012 demand curves to generate 2030 demand curve
%profiles.
%demandpostee2013: 2013 demand post-EE by state. From TSD demand side EE
%doc, 'EIA 861 Sales After EE (GWh)'. 

%Output arrays
demandchangeproportions=statesforanalysis;
demandbeforeee2013=statesforanalysis;
%Insert label for first col
demandchangeproportions=vertcat('State',demandchangeproportions);
demandbeforeee2013=vertcat('State',demandbeforeee2013);

for j=1:size(demandscenarioforanalysis,1)
    %Save scenario number in demandchangeproportions
    demandchangeproportions{1,j+1}=demandscenarioforanalysis(j,1);
    
    currscenario=demandscenarioforanalysis(j,1);
    
    %Import scenario data
    if strcmp(pc,'work')
        directoryforfiles='C:\Users\mtcraig\Desktop\EPP Research\Databases\EPA IPM Final Clean Power Plan Files';
    elseif strcmp(pc,'personal')
        directoryforfiles='C:\Users\mcraig10\Desktop\EPP Research\Databases\EPA IPM Final Clean Power Plan Files';
    end
    [~,~,eesavingsdata]=xlsread(fullfile(directoryforfiles,'df-cpp-demand-side-ee-at3.xlsx'),'Savings_Cumulative');
    [~,~,bausalesdata]=xlsread(fullfile(directoryforfiles,'df-cpp-demand-side-ee-at3.xlsx'),'Sales');
    
    %Trim top 2 rows
    eesavingsdata(1:2,:)=[];
    bausalesdata(1:2,:)=[];
    
    %1st row = data label; 2nd row = year; first col has State name; 2nd
    %col has state abbrev
    statenamecol=1; yearrow=2; datalabelsrow=1;
    
    %Turn years into strings
    for i=1:size(eesavingsdata,1)
        if isnan(eesavingsdata{yearrow,i})==0
            eesavingsdata{yearrow,i}=num2str(eesavingsdata{yearrow,i});
        end
    end
    for i=1:size(bausalesdata,1)
        if isnan(bausalesdata{yearrow,i})==0
            bausalesdata{yearrow,i}=num2str(bausalesdata{yearrow,i});
        end
    end
    
    %Get starting column for data in each case
    bausalesstartcol=find(strcmp(bausalesdata(datalabelsrow,:),'Sales before EE (GWh)'));
    eesalesaspercentstartcol=find(strcmp(eesavingsdata(datalabelsrow,:),'Net Cumulative Savings as a Percent of Sales Before EE (%)'));
    
    %Get 2013 and 2030 column for data of interest
    year2013colbau=find(strcmp(bausalesdata(yearrow,bausalesstartcol:end),'2013'));
    year2013colbau=year2013colbau(1)+bausalesstartcol-1; %might hav emany 2013 years for subsequent data sets,
    %so take 1st incidence of 2013, add to it col # where BAU sales begin,
    %then subtract 1.
    year2030colbau=find(strcmp(bausalesdata(yearrow,bausalesstartcol:end),'2030'));
    year2030colbau=year2030colbau(1)+bausalesstartcol-1;
%     year2013colee=find(strcmp(eesavingsdata(yearrow,eesalesaspercentstartcol:end),'2013'));
%     year2013colee=year2013colee(1)+eesalesaspercentstartcol-1;
    year2030colee=find(strcmp(eesavingsdata(yearrow,eesalesaspercentstartcol:end),'2030'));
    year2030colee=year2030colee(1)+eesalesaspercentstartcol-1;
    
    %Find state data
    for i=2:size(demandchangeproportions,1) %2 b/c 1st col is labels
        %Get row where state data begins
        rowofstateindata=find(strcmp(eesavingsdata(:,statenamecol),demandchangeproportions{i,1}));
        
        %Get 2013 sales before EE (ref point)
        salesbeforeee2013=bausalesdata{rowofstateindata,year2013colbau}; 
        
        %Now get 2030 sales before EE - need in both cases.
        salesbeforeee2030=bausalesdata{rowofstateindata,year2030colbau}; 
        
        %If using EE scenario, now get cumulative EE savings as % of pre-EE
        %2030 demand.
        if currscenario==1 
            %Get EE cumulative % savings (as % of 2030 pre-EE demand)
            eesavingscumulative2030=eesavingsdata{rowofstateindata,year2030colee};
            
            %Scale according to scaleenergyefficiencysavings
            eesavingscumulative2030=eesavingscumulative2030*scaleenergyefficiencysavings;
            
            salesafteree2030=salesbeforeee2030-(salesbeforeee2030*eesavingscumulative2030);
        end
        
        %Now get demand change proportion. For no EE,
        %(BAU2030-BAU2013)/BAU2013. For EE, (PostEE2030-BAU2013)/BAU2013.
        if currscenario==1 %1%/yr EE
            growthinsales2013to2030=(salesafteree2030-salesbeforeee2013)/salesbeforeee2013;
        elseif currscenario==0 %no EE
            growthinsales2013to2030=(salesbeforeee2030-salesbeforeee2013)/salesbeforeee2013;
        end

        %Save values in array
        demandchangeproportions{i,j+1}=growthinsales2013to2030;
        demandbeforeee2013{i,j+1}=salesbeforeee2013;        
    end
end





